server:
  port: 3011

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: table-service
  datasource:
    url: jdbc:mysql://localhost:3306/TableDB?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: restaurant_secret_key_12345678900
  expiration: 86400000
