server:
  port: 3007
  address: 127.0.0.1

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: image-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

upload:
  dir: uploads

