server:
  port: 3005

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: restaurant_secret_key_12345678900
  expiration: 86400000

app:
  base-url: ${APP_BASE_URL:http://localhost:3000}
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3001}
