server:
  port: 3003

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

services:
  table: http://localhost:3011
  menu: http://localhost:3002
  kitchen: http://localhost:3004
  payment: http://localhost:3008
  inventory: ${INVENTORY_SERVICE_URL:http://localhost:3006}

