server:
  port: 3000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowCredentials: true
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: user-service
          uri: http://localhost:3005
          predicates:
            - Path=/api/users/**
        
        - id: menu-service
          uri: http://localhost:3002
          predicates:
            - Path=/api/menu/**

        - id: order-service
          uri: http://localhost:3003
          predicates:
            - Path=/api/orders/**

        - id: table-service
          uri: http://localhost:3011
          predicates:
            - Path=/api/tables/**

        - id: kitchen-service
          uri: http://localhost:3004
          predicates:
            - Path=/api/kitchen/**

        - id: inventory-service
          uri: http://localhost:3006
          predicates:
            - Path=/api/inventory/**

        - id: payment-service
          uri: http://localhost:3008
          predicates:
            - Path=/api/payments/**

        - id: image-service
          uri: http://localhost:3007
          predicates:
            - Path=/api/images/**

        - id: payment-websocket
          uri: http://localhost:3008
          predicates:
            - Path=/ws/payment/**

        - id: kitchen-websocket
          uri: http://localhost:3004
          predicates:
            - Path=/ws/kitchen/**

        - id: order-websocket
          uri: http://localhost:3003
          predicates:
            - Path=/ws/order/**
