spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menudb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ""

services:
  inventory: http://localhost:3006
