spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ""

services:
  order: http://localhost:3003

momo:
  redirect-url-base: http://restaurant-server.site:3011/payment-return.html
  ipn-url: http://restaurant-server.site:3008/api/payments/momo/ipn

